### ISSUE TITLE
English documentation

### ISSUE THREAD

**Issue by francescosalvi** [tochka-developers/queue-promises#1]
any chance to have the dockblocks/readme in english?

**Comment by yekhlakov** [comment]
Hello!
Readme is translated into English, have a good day!

**Comment by francescosalvi** [comment]
Thank you!

**Comment by happyDemon** [comment]
could this be reopened? it's hard figuring out what the code does from the docblocks.

for example: `setPromiseFinishConditions` if I set both of them to true, does that mean the promise handler only gets run the first time there's a success/fail?

*edit* after running it through google translate, it seems it does
