### ISSUE TITLE
Request Alternative DB

### ISSUE THREAD

**Issue by xicond** [tochka-developers/queue-promises#13]
Is There any other possibility to store Promise tracker, 
like, redis ca be faster maybe,
because huge process, using DB seems pretty slow,

**Comment by darkdarin** [comment]
Hello. This package is used by us for our internal purposes, and therefore, in its implementation, the approaches that are necessary in our architecture are used.
Storing a chain of promises must be persistent and consistent in the first place. In addition, for production use, the solution must be scalable and resilient. In the event of a failure of the promise storage system, we must be able to quickly restore work, as well as not lose the data that was saved at the time of the accident.
Under these conditions, the use of the database closes all the problems - it is relatively easy to replicate, during replication you can be sure of data consistency, as well as fast recovery from failures.
Unfortunately, Redis cannot satisfy the specified circumstances. If you use Redis in one instance, this violates the principle of fault tolerance, and the Redis Сluster cannot provide consistency (this is indicated in their documentation). In addition, when using a Redis Сluster in a synchronous mode, the biggest advantage of a Redis, as speed, is lost. Therefore, for large fault-tolerant applications, using Redis for the promise storage system is not a good solution.
Therefore, we do not plan to add support for the specified DB.
But you can also contribute to the development of the package by publishing Merge Reguest with the required modifications. In pre-release versions, the Registry abstraction has been added for working with a data source. If this is really necessary functionality for small projects, we will consider the proposed code for inclusion in the release.
